-- Easy Shop PostgreSQL schema. All identifiers use snake_case.
create table if not exists sys_user (
    id bigint generated by default as identity primary key,
    wechat_open_id varchar(100) unique,
    wechat_union_id varchar(100),
    username varchar(100),
    password_hash varchar(255),
    mobile varchar(32) unique,
    nickname varchar(100) not null default '',
    avatar_url text,
    enabled boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create table if not exists user_address (
    id bigint generated by default as identity primary key,
    user_id bigint not null references sys_user(id) on delete cascade,
    consignee varchar(100) not null,
    mobile varchar(32) not null,
    province varchar(50) not null,
    city varchar(50) not null,
    district varchar(50) not null,
    detail varchar(255) not null,
    is_default boolean not null default false,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now()
);

create table if not exists mall_category (
    id bigint generated by default as identity primary key,
    parent_id bigint references mall_category(id) on delete set null,
    name varchar(100) not null,
    icon_url text,
    sort_order integer not null default 0,
    enabled boolean not null default true,
    created_at timestamp with time zone not null default now()
);

create table if not exists mall_product (
    id bigint generated by default as identity primary key,
    category_id bigint not null references mall_category(id) on delete restrict,
    name varchar(200) not null,
    subtitle varchar(500),
    description text,
    min_price numeric(18,2) not null default 0,
    max_price numeric(18,2) not null default 0,
    is_on_sale boolean not null default false,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint ck_mall_product_price check (min_price >= 0 and max_price >= min_price)
);

create table if not exists mall_product_sku (
    id bigint generated by default as identity primary key,
    product_id bigint not null references mall_product(id) on delete cascade,
    sku_code varchar(100) not null unique,
    specification jsonb,
    price numeric(18,2) not null default 0,
    market_price numeric(18,2) not null default 0,
    stock integer not null default 0,
    locked_stock integer not null default 0,
    enabled boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint ck_sku_stock check (stock >= 0 and locked_stock >= 0 and locked_stock <= stock),
    constraint ck_sku_price check (price >= 0 and market_price >= 0)
);

create table if not exists mall_product_image (
    id bigint generated by default as identity primary key,
    product_id bigint not null references mall_product(id) on delete cascade,
    image_url text not null,
    sort_order integer not null default 0,
    is_primary boolean not null default false
);

create table if not exists mall_cart (
    id bigint generated by default as identity primary key,
    user_id bigint not null references sys_user(id) on delete cascade,
    product_id bigint not null references mall_product(id) on delete restrict,
    sku_id bigint not null references mall_product_sku(id) on delete restrict,
    quantity integer not null,
    checked boolean not null default true,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint uq_mall_cart_user_sku unique (user_id, sku_id),
    constraint ck_mall_cart_quantity check (quantity > 0)
);

create table if not exists mall_order (
    id bigint generated by default as identity primary key,
    order_no varchar(40) not null unique,
    user_id bigint not null references sys_user(id) on delete restrict,
    status varchar(20) not null default 'WaitPay',
    goods_amount numeric(18,2) not null default 0,
    freight_amount numeric(18,2) not null default 0,
    discount_amount numeric(18,2) not null default 0,
    payable_amount numeric(18,2) not null default 0,
    consignee varchar(100) not null,
    mobile varchar(32) not null,
    address varchar(500) not null,
    paid_at timestamp with time zone,
    shipped_at timestamp with time zone,
    finished_at timestamp with time zone,
    cancelled_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint ck_mall_order_amount check (goods_amount >= 0 and freight_amount >= 0 and discount_amount >= 0 and payable_amount >= 0)
);

create table if not exists mall_order_item (
    id bigint generated by default as identity primary key,
    order_id bigint not null references mall_order(id) on delete cascade,
    product_id bigint not null references mall_product(id) on delete restrict,
    sku_id bigint not null references mall_product_sku(id) on delete restrict,
    product_name varchar(200) not null,
    sku_code varchar(100) not null,
    unit_price numeric(18,2) not null,
    quantity integer not null,
    total_amount numeric(18,2) not null,
    constraint ck_order_item_quantity check (quantity > 0)
);

create table if not exists payment_record (
    id bigint generated by default as identity primary key,
    order_id bigint not null references mall_order(id) on delete restrict,
    payment_no varchar(64) not null unique,
    channel varchar(20) not null default 'WECHAT',
    status varchar(20) not null default 'Created',
    amount numeric(18,2) not null,
    external_transaction_no varchar(100),
    paid_at timestamp with time zone,
    created_at timestamp with time zone not null default now(),
    updated_at timestamp with time zone not null default now(),
    constraint ck_payment_amount check (amount >= 0)
);

create table if not exists sys_role (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    code varchar(100) not null unique,
    created_at timestamp with time zone not null default now()
);

create table if not exists sys_permission (
    id bigint generated by default as identity primary key,
    name varchar(100) not null,
    code varchar(150) not null unique,
    created_at timestamp with time zone not null default now()
);

create table if not exists sys_user_role (
    user_id bigint not null references sys_user(id) on delete cascade,
    role_id bigint not null references sys_role(id) on delete cascade,
    primary key (user_id, role_id)
);

create table if not exists sys_role_permission (
    role_id bigint not null references sys_role(id) on delete cascade,
    permission_id bigint not null references sys_permission(id) on delete cascade,
    primary key (role_id, permission_id)
);
