create table if not exists promotion_group_buy_activity (
    id bigint generated by default as identity primary key,
    product_id bigint not null references mall_product(id) on delete restrict,
    sku_id bigint not null references mall_product_sku(id) on delete restrict,
    leader_price numeric(18,2) not null,
    member_price numeric(18,2) not null,
    required_members integer not null,
    starts_at timestamp with time zone not null,
    ends_at timestamp with time zone not null,
    enabled boolean not null default true
);
create table if not exists promotion_group_buy_team (
    id bigint generated by default as identity primary key,
    activity_id bigint not null references promotion_group_buy_activity(id) on delete restrict,
    leader_user_id bigint not null references sys_user(id) on delete restrict,
    current_members integer not null default 1,
    status varchar(20) not null default 'Open',
    expires_at timestamp with time zone not null,
    created_at timestamp with time zone not null default now()
);
create table if not exists promotion_group_buy_member (
    id bigint generated by default as identity primary key,
    team_id bigint not null references promotion_group_buy_team(id) on delete cascade,
    user_id bigint not null references sys_user(id) on delete restrict,
    order_id bigint not null references mall_order(id) on delete restrict,
    created_at timestamp with time zone not null default now(),
    unique(team_id, user_id), unique(order_id)
);
create table if not exists promotion_flash_sale_activity (
    id bigint generated by default as identity primary key,
    product_id bigint not null references mall_product(id) on delete restrict,
    sku_id bigint not null references mall_product_sku(id) on delete restrict,
    sale_price numeric(18,2) not null,
    total_stock integer not null,
    sold_quantity integer not null default 0,
    per_user_limit integer not null default 1,
    starts_at timestamp with time zone not null,
    ends_at timestamp with time zone not null,
    enabled boolean not null default true
);
create table if not exists promotion_flash_sale_order (
    id bigint generated by default as identity primary key,
    activity_id bigint not null references promotion_flash_sale_activity(id) on delete restrict,
    user_id bigint not null references sys_user(id) on delete restrict,
    order_id bigint not null references mall_order(id) on delete restrict,
    quantity integer not null,
    created_at timestamp with time zone not null default now(),
    unique(activity_id, user_id), unique(order_id)
);
create table if not exists distribution_distributor (
    id bigint generated by default as identity primary key,
    user_id bigint not null unique references sys_user(id) on delete cascade,
    parent_distributor_id bigint references distribution_distributor(id) on delete set null,
    invite_code varchar(32) not null unique,
    commission_rate numeric(5,4) not null default 0.0500,
    enabled boolean not null default true,
    created_at timestamp with time zone not null default now()
);
create table if not exists distribution_commission (
    id bigint generated by default as identity primary key,
    distributor_id bigint not null references distribution_distributor(id) on delete restrict,
    order_id bigint not null unique references mall_order(id) on delete restrict,
    rate numeric(5,4) not null,
    amount numeric(18,2) not null,
    status varchar(20) not null default 'PENDING',
    created_at timestamp with time zone not null default now()
);
create index if not exists ix_group_buy_activity_time on promotion_group_buy_activity(enabled, starts_at, ends_at);
create index if not exists ix_flash_sale_activity_time on promotion_flash_sale_activity(enabled, starts_at, ends_at);
create index if not exists ix_distribution_commission_distributor on distribution_commission(distributor_id, status);
