create table if not exists mall_product_favorite (
    id bigint generated by default as identity primary key,
    user_id bigint not null references sys_user(id) on delete cascade,
    product_id bigint not null references mall_product(id) on delete cascade,
    created_at timestamptz not null default now(),
    unique(user_id, product_id)
);
create index if not exists ix_product_favorite_user_created on mall_product_favorite(user_id, created_at desc);
